config/routes.rb
Getinvoice::Application.routes.draw do

  resources :accounts
  resources :products
  namespace :admin do
	resources :invoices do
		get :autocomplete_product_name, :on => :member
    post :send_to_user, :on => :collection
	end
  end
  resources :payment_notifications do
	get :user_payment, :on => :collection
  end
  match 'product/find_unit_price/:id', :controller=>'products', :action => 'find_unit_price'
  devise_for :users, ActiveAdmin::Devise.config

  resources :homes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users do
    get "admin/login" => "devise/sessions#new"
    get "admin/register" => "devise/registrations#new"
  end

   root :to => 'homes#index'

end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
  belongs_to :invoice
  serialize :params
  after_create :mark_cart_as_purchased
  attr_accessible :params, :invoice_id, :status, :transaction_id
  
  def mark_cart_as_purchased
    if status == "Completed"
      invoice.update_attribute(:purchased_at, Time.now)
    end
  end
end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
protect_from_forgery :except => [:create]
  def index
    #PaymentNotification.create!(:params => params, :invoice_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
	#render :nothing => true
  end

  def show
    @payment_notification = PaymentNotification.find(params[:id])
  end

  def new
    @payment_notification = PaymentNotification.new
  end

def create
  PaymentNotification.create!(:params => params, :invoice_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
  render :nothing => true
end

def user_payment
	@invoice = Invoice.find(params[:id])
end

  def edit
    @payment_notification = PaymentNotification.find(params[:id])
  end

  def update
    @payment_notification = PaymentNotification.find(params[:id])
    if @payment_notification.update_attributes(params[:payment_notification])
      redirect_to @payment_notification, :notice  => "Successfully updated payment notification."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @payment_notification = PaymentNotification.find(params[:id])
    @payment_notification.destroy
    redirect_to payment_notifications_url, :notice => "Successfully destroyed payment notification."
  end
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/views/payment_notifications/_form.html.haml
= form_for @payment_notification do |f|
  = f.error_messages
  %p
    = f.label :params
    %br
    = f.text_area :params
  %p
    = f.label :cart_id
    %br
    = f.number_field :cart_id
  %p
    = f.label :status
    %br
    = f.text_field :status
  %p
    = f.submit

app/views/payment_notifications/edit.html.haml
- title "Edit Payment Notification"

= render 'form'

%p
  = link_to "Show", @payment_notification
  |
  = link_to "View All", payment_notifications_path

app/views/payment_notifications/index.html.haml
- title "Payment Notifications"

%table
  %tr
    %th Params
    %th Cart
    %th Status
  - for payment_notification in @payment_notifications
    %tr
      %td= payment_notification.params
      %td= payment_notification.cart_id
      %td= payment_notification.status
      %td= link_to 'Show', payment_notification
      %td= link_to 'Edit', edit_payment_notification_path(payment_notification)
      %td= link_to 'Destroy', payment_notification, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Payment Notification", new_payment_notification_path

app/views/payment_notifications/new.html.haml
- title "New Payment Notification"

= render 'form'

%p= link_to "Back to List", payment_notifications_path

app/views/payment_notifications/show.html.haml
- title "Payment Notification"

%p
  %strong Params:
  = @payment_notification.params
%p
  %strong Cart:
  = @payment_notification.cart_id
%p
  %strong Status:
  = @payment_notification.status

%p
  = link_to "Edit", edit_payment_notification_path(@payment_notification)
  |
  = link_to "Destroy", @payment_notification, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", payment_notifications_path