config/routes.rb
Getinvoice::Application.routes.draw do

  resources :accounts
  resources :products
  namespace :admin do
	resources :invoices do
		get :autocomplete_product_name, :on => :member
    post :send_to_user, :on => :collection
	end
  end
  resources :payment_notifications do
	get :user_payment, :on => :collection
  end
  match 'product/find_unit_price/:id', :controller=>'products', :action => 'find_unit_price'
  devise_for :users, ActiveAdmin::Devise.config

  resources :homes

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users do
    get "admin/login" => "devise/sessions#new"
    get "admin/register" => "devise/registrations#new"
  end

   root :to => 'homes#index'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    #@homes = Home.all
  end

  def show
    @home = Home.find(params[:id])
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(params[:home])
    if @home.save
      redirect_to @home, :notice => "Successfully created home."
    else
      render :action => 'new'
    end
  end

  def edit
    @home = Home.find(params[:id])
  end

  def update
    @home = Home.find(params[:id])
    if @home.update_attributes(params[:home])
      redirect_to @home, :notice  => "Successfully updated home."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @home = Home.find(params[:id])
    @home.destroy
    redirect_to homes_url, :notice => "Successfully destroyed home."
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.haml
= form_for @home do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit

app/views/homes/edit.html.haml
- title "Edit Home"

= render 'form'

%p
  = link_to "Show", @home
  |
  = link_to "View All", homes_path

app/views/homes/index.html.haml
#outerWrapDiv.container
  #innerWrapDiv.mktEditable
    #container.container_16
      .grid_16
        #mktHeader.header
          %h1.branding
            Create Your Invoice in Minutes
      .grid_16
        #content.box.shadow.mktEditable
          #textarea
            #lpeCDiv_3928.lpeCElement
              %span.lpContentsItem.richTextSpan
                %div
                  %a.trackLink.lightbox.cboxElement{:_mce_href => "#", :href => "#"}
                    %img#ExtBox1-ext-gen1300{:_mce_src => "#{asset_path('1.JPEG')}", :_mce_style => "border: 1px solid #cacaca; display: block; margin-left: auto; margin-right: auto;", :height => "384", :src => "#{asset_path("1.JPEG")}", :style => "border: 1px solid #cacaca; display: block; margin-left: auto; margin-right: auto;", :width => "450"}/
                  %br{:_mce_bogus => "1"}/
                %h3  GetInvoice Platform as a Service
                %p GetInvoice provide easy to generate and record your daily invoces.It solutions that enable you to record incomming and out going products, so that you deploy more quickly, scale with ease.
              
            #lpeCDiv_3930.lpeCElement
              .lpContentsItem.rawHtmlSpan
                %script{:src => "", :type => "text/javascript"}
                :css
                  body#fullwidth #content h3 { font-weight: bold; color: #000000; }
                  #cta_button { width: 342px; font-size: 16px; line-height: 30px; padding: 10px 0; font-weight:normal; margin-bottom:34px; } 
                  
                  #cta_button_alt { text-shadow: 0 1px 0 #759423; width: 342px; font-size: 32px; line-height: 30px; padding: 10px 0; font-weight:normal; margin-bottom:15px; border: 1px solid #6f8a1d; background: #6f8a1d; background: -moz-linear-gradient(top, #a6bb43, #759423); background: -webkit-gradient(linear, left top, left bottom, from(#a6bb43), to(#759423)); }
                  a.trackLink img, #open_source_logos { border:1px solid #000; }
                  #open_source_logos {margin-bottom: 36px;}
                  #customer_quote blockquote, #customer_quote cite {   color: #2886BB;   font-family: "proxima-nova-1","proxima-nova-2",Arial,"Liberation Sans",FreeSans,sans-serif; }
                  #customer_quote blockquote, 
                  #customer_quote cite { margin: 0; }
                  li { font-size: 12px; }
                %div
                  %a#cta_button_alt.button.center{:href => "/admin"}
                    GetInvoice is free
                    %br
                      %span{:style => "font-size:16px;"} Sign-up today, no credit card required
                %h3
                  %strong Here's What You Get
                %ul
                  %li GetInvoice is free
                  %li A full-featured generate and record invoices
                  %li Can manage incomming and outgoing products
                  %li
                    Secure data 
                  %li
                    Online payment option
                %br
                  %br
                    %br
                      #customer_quote
                        %blockquote 
                          The best invoice generator, I have found for my shope.
                          %br
                          Now I can keep record of my custumers, books and their invoices. Thanks Nand.
                        %city.right 
                          Financial World Bookshop, City of London
                        


          #content_footer
      #footer.grid_16
        #footer-content
          .page
            .grid_3
              %h2
                %a{:href => "#"} Get Started
              %h2
                %a{:href => "/admin"} Sign In
            .grid_10
              %h2
                %a{:href => "#"} Contact Us
              %h2
                %a{:href => "#"} Documentation
              %h2
                %a{:href => "#"} Product Info
              %h2
                %a{:href => "#"} Privacy Policy
 

app/views/homes/new.html.haml
- title "New Home"

= render 'form'

%p= link_to "Back to List", homes_path

app/views/homes/show.html.haml
- title "Home"

%p
  %strong Name:
  = @home.name

%p
  = link_to "Edit", edit_home_path(@home)
  |
  = link_to "Destroy", @home, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", homes_path